"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Drop draop",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideFooter = pathname && pathname.startsWith("/profile");

  return (
    <html lang="fa" dir="ltr">
      <body
        className={` 'modal-bod-hidden':''} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {!hideFooter && <Header />}
        {children}
        {!hideFooter && <Footer />}
      </body>
    </html>
  );
}
